baseurl                 = "/"
relativeURLs            = true
languageCode            = "en-us"
defaultContentLanguage  = "en"
isMultilingual          = false
title                   = "Open Science Escape Room"
theme                   = "sam"
pygmentsStyle           = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
publishDir              = "docs"

[markup.goldmark.renderer]
      unsafe = true

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "images/favicon.png"
    homepage            = "home"                           # What to call the home page link
    header              = ""                               # Optional header for the home page (left empty by default for aesthetical reasons)
    footerText          = ""
    companylogo         = "images/favicon.png"
    logoheight          = "40px"
    companysite         = "https://www.med.uio.no/norment/english/"

# Metadata for Open Graph and Twitter
    description         = "Interactive site for a Virtual Open Science and Open Access Escape Room"
    images              = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title               = "Open Science Escape Room"
    # rss               = ""

[[params.videoBackground.sources]]
    # put a link to a video in the item below, you could .e.g save a video in the "images" folder and link to it like this: "source = "images/background_video.mp4""
    source  = "images/background_video.mp4"
    type    = "video/mp4"
    poster  = "images/background.jpg"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.6)" # optional

#[[params.mainMenu]]
#    link = "/items/closed"
#    text = "THE ESCAPE ROOM IS CLOSED"
[[params.mainMenu]]
    link = "introduction"
    text = "start"
[[params.mainMenu]]
    link = "tasks"
    text = "tasks"
[[params.mainMenu]]
    link = "instructions"
    text = "instructions"
[[params.mainMenu]]
    link = "about"
    text = "about"

[imaging]
    quality = 75
